---
title: "Week 4 Excercise"
author: "Mina Mehdinia"
date: '2022-04-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# In-class exercise 1
### relationship between Fertility and Agriculture

##### Is the relationship between Fertility and Agriculture negative?

```{r}
data("swiss")
str(swiss)

col.fer <- rep(c("firebrick","forestgreen","cornflowerblue"), 
               times=c(sum(swiss$Fertility<50),
                       sum(swiss$Fertility>=50&swiss$Fertility<70), 
                       sum(swiss$Fertility>=70)))
              
              
plot(x = swiss$Fertility, y = swiss$Agriculture,
     xlab = "Fertility", ylab = "Agriculture",
     main = "Fertility and Agriculture in 1888 Switzerland",
     col = col.fer,
     cex = 1, 
     type="p",
     pch=16,
     lty=1,
     lwd=1)
legend("topleft", 
       bty="y", 
       pch=16,
       col=c("firebrick","forestgreen","cornflowerblue"), 
       legend = c("fertility < 50","50 <= fertility < 70","fertility >= 70"))
```

### relationship between Education and Catholic

##### Is this relationship between education and catholic?

```{r}
col.edu <- rep(c("firebrick","forestgreen","cornflowerblue"), 
               times=c(sum(swiss$Education<50),
                       sum(swiss$Education>=50&swiss$Education<70), 
                       sum(swiss$Education>=70)))
              
              
plot(x = swiss$Education, y = swiss$Catholic,
     xlab = "Education", ylab = "Catholic",
     main = "Education and Catholic in 1888 Switzerland",
     col = col.edu,
     cex = 1, 
     type="p",
     pch=16,
     lty=1,
     lwd=1)
legend("topleft", 
       bty="y", 
       pch=16,
       col=c("firebrick","forestgreen","cornflowerblue"), 
       legend = c("Education < 50","50 <= Education < 70","Education >= 70"))
```

# In-class exercise 2

```{r}
par(mfrow=c(1,2))
plot(x = swiss$Fertility, y = swiss$Examination,
     main = "Fertility vs. Examination",
     xlab = "Fertility", ylab = "Examination",
     type = "p", 
     col = "pink",
     cex = 1,
     cex.main = .9,
     cex.lab = 1,
     cex.axis = 1,
     pch=16,
     lty=1,
     lwd=1)

hist(x = swiss$Infant.Mortality, freq = TRUE, col = "purple", cex.main = .9, main = "Histogram of Infant.Mortality")



nf <- layout(matrix(c(1,2,0,3), ncol=2, nrow=2, byrow=TRUE), widths=c(2,3), heights=c(2,2.5), respect=TRUE)
plot(x = swiss$Fertility, y = swiss$Examination,
     main = "Fertility vs. Examination",
     xlab = "Fertility", ylab = "Examination",
     type = "p", 
     col = "blue",
     cex = 1,
     cex.main = .9,
     cex.lab = 1,
     cex.axis = 1,
     pch=16,
     lty=1,
     lwd=1)

swiss$Catholic <- ifelse(swiss$Catholic <20,"Low",
                         ifelse(swiss$Catholic <70,"Medium","high"))
boxplot(Fertility~Catholic, data=swiss,
        col="firebrick",xlab = "Percentage of cathlic")


matplot(swiss$Examination, pch=1:4, col="lightgreen")
```


