---
title: "Week 2"
author: "Mina Mehdinia"
date: '2022-04-10'
output: html_document
---

## Week One
### Set 2
```{r}
primes = c( 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97)

x = c(3,4,12,19,23,51,61,63,78)

val = c()
i = x[1]
j = 1


for(a in primes){
  if(j>length(x)){
    break
  }
  while((i<=a)&(j<=length(x))){
    if(i!=a){
      val = c(val,i)
    }
    j = j+1
    i = x[j]
  }
}
val


```
## Week two
### Set 1
#### problem 1

```{r}
#the type of this vector is character because of "c" that been included. and character cannot be coereced into an integer, therefore the whole is character. 
typeof(c(1, NA+1L, "C"))


#the type of this vector is double because type of(c(1L/0)) is double and type of NA is logical, and logical can be coerced into double, therefore the whole vector is double
typeof(c(1L / 0, NA))


#the type of vector is double because the type of 1:3 in integer and type of 5 in double and integer can be coerced into double, therefore the whole vector type is double
typeof(c(1:3, 5))


#the type of vector is double because the type of 3L in integer and type of NAN+1L is double and integer can be coerced into double, therefore, the whole vector is double
typeof(c(3L, NaN+1L))


#the type of vector is Logical because the type of both NA and TRUE are logical
typeof(c(NA, TRUE))
```

#### problem 2
```{r}
#1
paste("Label",1:30)

#2
paste("fn",1:30,sep = "")
```
### Set 2
```{r}
TheList <- list(firstName = "John",
                lastNAme = "Smith",
                age = "25",
                address = list(streetAddress = "31 3rd Street",
                               city = "New York",
                               State = "NY",
                               postalCode = 10021),
                phoneNumber = list(list(type = "home",
                                        number = "212 555-5555"),
                                   list(type = "fax",
                                        number = "646 555-5555")))
str(TheList)
```

### Set 3
```{r}
x <- c(1L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 3L, 4L, 3L, 4L)
levelx <- c("sun", "partial clouds","clouds","rain","snow")

attr(x,"levels") = levelx
attr(x,"class") = "factor"
x





```

